[discord]
token = "sosi4len"

[bot]
prefix = "."

[messages.errors.success_line]
emoji = "<:normal_line:749986920578416734>"
repeat = 14
color = 0x6ee51f

[messages.errors.standard_line]
emoji = "<:standart_line:749988256350863461>"
repeat = 14
color = 0xadadad

[messages.errors.error_line]
emoji = "<:error_line:749986920700051518>"
repeat = 14
color = 0xff3d43 

[messages.errors]
invisible_symbol = "⠀"
